version: '3.8'
services: 
  mysql:
    image: mysql
    build: .
    restart: always
    environment:
      MYSQL_USER: ltl
      MYSQL_PASSWORD: ltl
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 6000:3306
    volumes:
      - "./dbdata:/var/lib/mysql"
  api:
    build: .
    container_name: api
    restart: always
    depends_on:
      - mysql
    ports:
      - 80:80
    volumes:
      - "./storage:/app/publish/Storage"


